### ISSUE TITLE
List<string>类型Update时报错

### ISSUE THREAD

**Issue by 406224330** [loogn/Loogn.OrmLite#1]
这是给的例子：
//整体修改，添加时忽略
        [OrmLiteField(Ignore = true)] 
        public List<string> SomeAttrs { get; set; }
这是错误内容：
![image](https://user-images.githubusercontent.com/21120585/46996729-4af59f00-d150-11e8-8f2a-73098df06ea5.png)
![image](https://user-images.githubusercontent.com/21120585/46996832-8bedb380-d150-11e8-95aa-aac1c2abc9b7.png)

**Comment by loogn** [comment]
@406224330  已修复，nuget上稍后发布
