### ISSUE TITLE
db.SelectPage<dynamic> 取不到值 类型为{object}

### ISSUE THREAD

**Issue by 406224330** [loogn/Loogn.OrmLite#2]
![image](https://user-images.githubusercontent.com/21120585/47196387-dc545380-d392-11e8-8104-3183c3cfb009.png)
![image](https://user-images.githubusercontent.com/21120585/47196407-eaa26f80-d392-11e8-9077-a70b2bf5c67f.png)
{ "code": 0, "msg": "", "count": 1, "data": [ {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {} ] }

**Comment by loogn** [comment]
@406224330 如果返回dynamic的话，直接使用db.SelectPage(new OrmLitePageFactor{})即可，不用使用泛型，db.SelectPage内部调用错了方法，现在已修复。不过还是建议您使用强类型的模型类调用！
